#include "DBScanAlgorithm.h"
#include "FORELAlgorithm.h"
#include "HierarchicalAlgorithm.h"
#include "KMeansAlgorithm.h"
#include "SpanningTreeAlgorithm.h"
#include "WaveAlgorithm.h"
#include "EMAlgorithm.h"